### PR TITLE
Fixes a problem with camera enumeration and resynching of IMU data with camera frames.

### PR DESCRIPTION
**Pull request by jywilson**

### CODE REVIEW

**Comment by ChristophTobler** [comment]
@jywilson Thank you! I'll have a look at it

**Comment by ChristophTobler** [comment]
@jywilson I wanted to test this PR but I always get the error:
```[ERROR] IMU buffer is empty [/home/linaro/src/snap_cam/src/optical_flow.cpp:327]```
I have added the lines:
```
mavlink start -u 14557 -r 1000000 -t 127.0.0.1 -o 14558 
mavlink stream -u 14557 -s HIGHRES_IMU -r 250
```
to ```/usr/share/data/adsp/px4.config```. I think I don't receive any mavlink messages since I never enter this if statement https://github.com/PX4/snap_cam/blob/master/src/optical_flow.cpp#L592

Am I missing something?

**Comment by jywilson** [comment]
I have been running my tests with the the mavlink commands in mainapp.config not px4.config.  The commands in px4.config run on the aDSP, not the AppsProc (ARM processor).  You need the mavlink streams to run on the AppsProc in order to communicate with the ROS nodes.  

Jim W.

**Comment by lucasilvestri** [comment]
So this guide is wrong, it says px4.config
https://dev.px4.io/optical_flow.html

**Comment by ChristophTobler** [comment]
@lucasilvestri Yes. I'll change that. Thanks

**Comment by ChristophTobler** [comment]
@jywilson FYI: right now I'm stuck with this: https://github.com/PX4/Firmware/issues/6636

With the part commented in the commander.cpp I get weird IMU data and if I run the `optical_flow` I get
```
[ERROR] IMU buffer is empty [/home/linaro/src/snap_cam/src/optical_flow.cpp:327]
[ERROR] IMU buffer is empty [/home/linaro/src/snap_cam/src/optical_flow.cpp:327]
[ERROR] IMU buffer is empty [/home/linaro/src/snap_cam/src/optical_flow.cpp:327]
[ERROR] IMU buffer is empty [/home/linaro/src/snap_cam/src/optical_flow.cpp:327]
[ERROR] IMU buffer is empty [/home/linaro/src/snap_cam/src/optical_flow.cpp:327]
[ERROR] IMU buffer is empty [/home/linaro/src/snap_cam/src/optical_flow.cpp:327]
[ERROR] IMU buffer is empty [/home/linaro/src/snap_cam/src/optical_flow.cpp:327]
[ERROR] IMU buffer is empty [/home/linaro/src/snap_cam/src/optical_flow.cpp:327]
[ERROR] IMU buffer is empty! Last IMU time 352074008, new image time 348516701, dt -3557307 [/home/linaro/src/snap_cam/src/optical_flow.cpp:360]
```
I appended
```
mavlink start -u 14557 -r 1000000 -t 127.0.0.1 -o 14558 
mavlink stream -u 14557 -s HIGHRES_IMU -r 250
```
to `mainapp.config`

**Comment by ChristophTobler** [comment]
merged

**Pull request closed without merging**
